### ISSUE TITLE
[Feature request] Add option to limit max number of saved replays (rolling replays)

### ISSUE THREAD

**Issue by Al12rs** [ubelhj/AutoSavePrivateReplay#2]
It would be cool to have an option to set a limit to the amount of replays that the plugin saves, to avoid spamming the replays folder with stuff you will never watch.

Once the limit is reached, the oldest automatic replay is deleted to be replaced with the latest one. So you always have your most recent replays but don't have to worry about flooding the replay folder and having do go and delete them.

Personally I would probably set this between 3 and 10 for myself, so that I can have the matches of the day and perhaps the ones from the day before.

Do you think this is something you would be interested in adding in your plugin?

**Comment by ubelhj** [comment]
Unfortunately, this feature would require a lot of additional logic. The plugin was basically a bet that I could make a mod in 1 hour. Due to that simplicity and rush, it doesn't actually do any filesystem stuff. It just asks bakkesmod to save the replay, and bakkesmod handles all that. 

Adding logic to count how many replays are in your replay folder and deleting the oldest is totally possible, but I just don't think that's worth the effort. There's a good chance I might write bugs and delete people's old replays, which I really don't want to do. The effort needed would be equivalent to writing a whole new plugin from scratch. Maybe try using ballchasing and automatic replay upload to look at your latest replays when reviewing. 

If you want to learn how to make a plugin yourself, this might be a decent idea to start with! https://bakkesmodwiki.github.io

**Comment by Al12rs** [comment]
Yeah, it's a lot more than the original idea and I see how easy it would be for things to go wrong. 
I will have a look at uploading replay solutions.

Thanks again for taking the time to consider it and answer, I appreciate it!
